version: "3"
services:
  web:
    image: jmixtest/jmix-tm:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: tmDevDocker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root